---
- name: Ensure app dir exists
  file:
    path: "/var/www/{{ domain }}"
    state: directory
    owner: www-data
    group: www-data

- name: Ensure web root exists
  file:
    path: "/var/www/{{ domain }}/public"
    state: directory
    owner: www-data
    group: www-data

- name: Add PHP file
  copy:
    src: index.php
    dest: "/var/www/{{ domain }}/public/index.php"
    owner: www-data
    group: www-data

- name: Remove default Nginx configurations
  command: rm -rf nginx/conf.d/.default.conf && rm -rf nginx/conf.d/no-ssl.default.conf
  args:
    chdir: /etc
  ignore_errors: yes

# https://github.com/h5bp/server-configs-nginx
# conf.d/: This directory should contain all the server definitions.
# Except if they are dot prefixed or non .conf extension,
# all files in this folder are loaded automatically.
- name: Add Nginx configuration
  template:
    src: "{{ domain }}.j2"
    dest: "/etc/nginx/conf.d/{{ domain }}.conf"
    owner: root
    group: root

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded
