---
- name: Create Admin User
  user:
    name: admin
    password: "{{ admin_password | password_hash('sha512') }}"
    groups: sudo
    append: true # add the user to group `sudo`
    shell: /bin/bash
