---
# https://docs.ansible.com/ansible/latest/collections/ansible/builtin/user_module.html
# These Tasks use the user module to create new users,
# passing in the passwords set in the Variable file.
- name: Create Admin User
  user:
    name: admin
    # password: "{{ admin_password | password_hash('sha512') }}"
    # Defines the primary group for the user
    groups: admin
    shell: /bin/bash

# https://docs.ansible.com/ansible/latest/collections/ansible/posix/authorized_key_module.html
# Add the SSH public key
- name: Add Admin Authorized Key
  authorized_key:
    user: admin
    state: present
    key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

- name: Add admin user to the sudoers
  copy:
    dest: "/etc/sudoers.d/admin"
    content: "%admin ALL=(ALL) NOPASSWD: ALL"

- name: Disable Password Authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
    state: present
    backup: yes

- name: Disable Root Login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
    state: present
    backup: yes
  notify:
    - restart ssh
