---
- name: Create Deploy User
  user:
    name: deploy
    groups: www-data
    append: true
    shell: /bin/bash

- name: Add Deployer Authorized Key
  authorized_key:
    user: deploy
    state: present
    key: "{{ item }}"
  with_file:
    - ./id_ed25519.pub

- name: Remove home
  shell: rm -rf /var/www/*
