---
- name: Ensure app dir exists
  file:
    path: /var/www/experiment.com
    state: directory
    owner: www-data
    group: www-data

- name: Ensure web root exists
  file:
    path: /var/www/experiment.com/public
    state: directory
    owner: www-data
    group: www-data

- name: Add PHP file
  copy:
    src: index.php
    dest: /var/www/experiment.com/public/index.php
    owner: www-data
    group: www-data

- name: Remove default Nginx configurations
  command: rm -rf nginx/conf.d/.default.conf && rm -rf nginx/conf.d/no-ssl.default.conf
  args:
    chdir: /etc
  ignore_errors: yes

# https://www.linode.com/docs/guides/how-to-configure-nginx/
# Installation from official NGINX repository: include directive is include
# /etc/nginx/conf.d/*.conf;. Every website you host with NGINX gets it’s
# own configuration file in /etc/nginx/conf.d/, with names formatted as example.com.conf.
- name: Add Nginx configuration
  copy:
    src: experiment.com.conf
    dest: /etc/nginx/conf.d/experiment.com.conf
    owner: root
    group: root

- name: Reload Nginx
  service:
    name: nginx
    state: reloaded
