---
# playbook.yml
- name: "Provision Image"
  # https://ansible-docs.readthedocs.io/zh/stable-2.0/rst/playbooks_intro.html#hosts-and-users
  # The hosts line is a list of one or more groups or host patterns.
  # hosts: localhost
  # hosts: all # every server in etc/ansible/hosts
  hosts: default # use the host that we run this in.
  # https://ansible-docs.readthedocs.io/zh/stable-2.0/rst/become.html
  # When become = yes and become_user is not mentioned
  # the task would by default be run as root user
  # Ansible become_user is to run a particular task as a specific user
  # == sudo -u <username>
  become: true

  tasks:
    - name: Initial pause to let Ubuntu finish unattended updates
      pause:
        minutes: 1

    # curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add
    - name: Add Hashicorp Key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present

    # sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main
    - name: Add Hashicorp Repos
      apt_repository:
        repo: deb https://apt.releases.hashicorp.com focal main
        state: present

    - name: Install packages
      apt:
        name: "{{ item }}"
        state: present
        # https://docs.ansible.com/ansible/latest/collections/ansible/builtin/apt_module.html#parameter-update_cache
        # === apt-get update
        update_cache: true
      loop:
        - nginx
        - zsh
        - terraform
        - python3-venv

    - name: Download Go
      get_url:
        url: https://golang.org/dl/go1.17.2.linux-amd64.tar.gz
        dest: /tmp/go.tar.gz

    - name: Extract Go Tarball
      unarchive:
        src: /tmp/go.tar.gz
        dest: /usr/local
        copy: no

    - name: Add 'mmegger' user
      user:
        name: mmegger
        shell: /bin/zsh
        groups: sudo

    - name: Create mmegger .ssh directory
      file:
        path: /home/mmegger/.ssh
        state: directory
        owner: mmegger
        group: mmegger
        mode: "0700"

    - name: install oh my zsh
      become: yes
      become_user: mmegger
      shell: sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    - name: perform commands as mmegger
      become: yes
      become_user: mmegger
      git:
        repo: https://github.com/MasonEgger/dotfiles.git
        version: master
        dest: /home/mmegger/dotfiles

    - name: copy dotfiles
      become: yes
      become_user: mmegger
      copy:
        remote_src: yes
        src: /home/mmegger/dotfiles/{{ item }}
        dest: /home/mmegger/{{ item }}
        owner: mmegger
        group: mmegger
        mode: "0644"
      loop:
        - .zshrc
        - .vimrc
