---
- name: Set up application
  hosts: all
  become: yes
  vars:
    - domain: experiment.com
    - repo: https://github.com/pkboom/experiment.git
    - db_name: experiment
    - db_user: admin
    - db_password: asdfasdf

  tasks:
    - name: Delete existing project
      file:
        state: absent
        path: /var/www

    - name: Clone
      git:
        repo: "{{ repo }}"
        dest: /var/www/{{ domain }}

    - name: Recursively change ownership of directoris and files
      file:
        path: /var/www/{{ domain }}
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
        mode: u=rwX,g=rwX,o=rX

    - name: Install nodejs
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash -
        sudo apt-get install -y nodejs

    - name: Install packages
      become: true
      become_user: admin
      shell: |
        cp '.env.example' '.env'
        composer install
        php artisan key:generate
        npm install
        npm run build
      args:
        chdir: /var/www/{{ domain }}
      register: output

    - debug:
        var: output.stdout_lines

    - name: Configure DB_DATABASE
      lineinfile:
        dest: "/var/www/{{ domain }}/.env"
        state: "present"
        regexp: "^DB_DATABASE"
        line: "DB_DATABASE={{ db_name }}"

    - name: Configure DB_USERNAME
      lineinfile:
        dest: "/var/www/{{ domain }}/.env"
        state: "present"
        regexp: "^DB_USERNAME"
        line: "DB_USERNAME={{ db_user }}"

    - name: Configure DB_PASSWORD
      lineinfile:
        dest: "/var/www/{{ domain }}/.env"
        state: "present"
        regexp: "^DB_PASSWORD"
        line: "DB_PASSWORD={{ db_password }}"

    - name: Migrate
      command: php artisan migrate
      args:
        chdir: "/var/www/{{ domain }}"
      with_items:
        - php artisan migrate
