---
- name: Set up application
  hosts: all
  become: yes
  vars:
    - domain: experiment.com
    - repo: git@github.com:pkboom/experiment.git
    - db_name: experiment
    - db_user: admin
    - db_password: asdfasdf
    - php_version: 8.2

  tasks:
    - name: Delete existing project
      file:
        state: absent
        path: /var/www

    - name: Create www dir
      file:
        path: /var/www
        state: directory
        owner: admin
        group: admin
        mode: 0775

    - name: Clone
      become: true
      become_user: admin
      git:
        repo: "{{ repo }}"
        dest: /var/www/{{ domain }}
        depth: 1
        single_branch: yes
        version: master
        accept_hostkey: true
        # key_file: ~/.ssh/id_ed25519

    - name: Fix unsafe repository
      become: true
      become_user: admin
      command: git config --global --add safe.directory /var/www/{{ domain }}

    - name: Recursively change ownership of directoris and files
      file:
        path: /var/www/{{ domain }}
        state: directory
        recurse: yes
        owner: www-data
        group: www-data
        mode: u=rwX,g=rwX,o=rX

    - name: Create .env
      become: true
      become_user: admin
      shell: cp '.env.example' '.env'
      args:
        chdir: /var/www/{{ domain }}

    - name: Configure DB_PASSWORD
      become: true
      become_user: admin
      lineinfile:
        dest: "/var/www/{{ domain }}/.env"
        state: "present"
        regexp: "^{{ item.name }}"
        line: "{{ item.name }}={{ item.value }}"
      loop:
        - { name: "DB_DATABASE", value: "{{ db_name }}" }
        - { name: "DB_USERNAME", value: "{{ db_user }}" }
        - { name: "DB_PASSWORD", value: "{{ db_password }}" }

    - name: Install nodejs
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash -
        sudo apt-get install -y nodejs

    - name: Install packages
      become: true
      become_user: admin
      shell: |
        composer install
        php artisan key:generate
        npm install
        npm run build
      args:
        chdir: /var/www/{{ domain }}
      register: output

    - debug:
        var: output.stdout_lines

    - name: Migrate
      become: true
      become_user: admin
      command: php artisan migrate
      args:
        chdir: "/var/www/{{ domain }}"

    - name: Restart PHP-FPM
      service:
        name: "php{{ php_version }}-fpm"
        state: restarted
