---
- name: Set up application
  hosts: all
  become: yes
  vars:
    - domain: bionic
    - domain: bionic

  tasks:
    - name: Install nodejs
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_19.x | sudo -E bash - &&\
        sudo apt-get install -y nodejs
