---
- name: Generating a new SSH key
  shell: |
    ssh-keygen -q -t rsa -b 4096 -f ~/.ssh/github_actions -N ''

- name: Create Deploy User
  user:
    name: deploy
    password: "{{ deploy_password | password_hash('sha512') }}"
    groups: www-data
    append: true
    shell: /bin/bash

- name: Add Deployer Authorized Key
  authorized_key:
    user: deploy
    state: present
    key: "{{ item }}"
  with_file:
    - ~/.ssh/github_actions.pub

- name: Remove home
  shell: rm -rf /var/www/*

- name: Clone and set up
  shell: git clone {{ repository }} {{ domain }}
  args:
    chdir: /var/www

- name: Clone and set up
  shell: |
    composer install
    # copy '.env.example' '.env'
    # npm install
    # php artisan key:generate
    # npm run dev
  args:
    chdir: /var/www/{{ domain }}
  register: command_output

- debug:
    var: command_output.stdout_lines

- name: Configure DB_DATABASE
  lineinfile:
    dest: "/var/www/{{ domain }}/.env"
    state: "present"
    regexp: "^DB_DATABASE"
    line: "DB_DATABASE={{ db_name }}"

- name: Configure DB_USERNAME
  lineinfile:
    dest: "/var/www/{{ domain }}/.env"
    state: "present"
    regexp: "^DB_USERNAME"
    line: "DB_USERNAME={{ db_user }}"

- name: Configure db
  lineinfile:
    dest: "/var/www/{{ domain }}/.env"
    state: "present"
    regexp: "^DB_PASSWORD"
    line: "DB_PASSWORD={{ db_password }}"

- name: Migrate
  command: "{{ item }}"
  args:
    chdir: "/var/www/{{ domain }}"
  with_items:
    - php artisan migrate
