---
- name: Add PHP Repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Install PHP and PHP-FPM
  apt:
    pkg:
      [
        "php8.2-fpm",
        "php8.2-cli",
        "php8.2-mysql",
        "php8.2-sqlite3",
        "php8.2-curl",
        "php8.2-gd",
        "php8.2-intl",
        "php8.2-imap",
        "php8.2-ldap",
        "php8.2-mbstring",
        "php8.2-xml",
        "php8.2-zip",
        "php8.2-bz2",
        "php8.2-imagick",
        "php8.2-bcmath",
        "php8.2-soap",
        "php8.2-readline",
        "php8.2-memcached",
        "php8.2-msgpack",
        "php8.2-igbinary",
        "php8.2-redis",
      ]
    state: present
    update_cache: true

- name: Install Composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

- name: Make Composer Executable
  shell: chmod a+x /usr/local/bin/composer

- name: Composer Self Update
  shell: composer self-update

- name: Add PHP-FPM PHP Configuration
  copy:
    src: php.ini
    dest: /etc/php/8.2/fpm/php.ini
    owner: root
    group: root

- name: Add PHP-FPM Pool Configuration
  copy:
    src: www.conf
    dest: /etc/php/8.2/fpm/pool.d/www.conf
    owner: root
    group: root

- name: Restart PHP-FPM
  service:
    name: php8.2-fpm
    state: restarted
